name: Build and Deploy React App to Azure Web App

on:
  push:
    branches:
      - main  # Trigger deployment on push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          cd frontend
          npm ci  # faster and reproducible than npm install

      # 4. Build the React app
      - name: Build React app
        run: |
          cd frontend
          npm run build

      # 5. Deploy to Azure Web App using Publish Profile
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ANEMIAlabassist
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: frontend/build
